CREATE TABLE "ACCOUNT" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "NAME" VARCHAR(30) NOT NULL,
    "DESCRIPTION" VARCHAR(255),
    "CREATIONDATE" DATE NOT NULL,
    "CANCELLATIONDATE" DATE
);

CREATE TABLE "PAYMENT" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "ACCOUNTID" BIGINT REFERENCES ACCOUNT (ID),
    "DESCRIPTION" VARCHAR(255) NOT NULL,
    "DATE" DATE NOT NULL,
    "AMOUNT" DECIMAL(12,2) NOT NULL
);
