INSERT INTO ACCOUNT (NAME, DESCRIPTION, CREATIONDATE) VALUES ('MujUcet','Nejlepsiucet','2015-02-10');

INSERT INTO ACCOUNT (NAME, DESCRIPTION, CREATIONDATE) VALUES ('MujUcet2','Nejlepsiucet2','2015-02-15');

INSERT INTO ACCOUNT (NAME, DESCRIPTION, CREATIONDATE) VALUES ('MujUcet3','Student ucer','2014-02-15');